// This file contains 365 high-energy motivational videos under 10 minutes.
const videos = [
  { title: "Rise and Shine", embedUrl: 'https://www.youtube.com/embed/hbkZrOU1Zag' },
  { title: "Shia LaBeouf \u2013 Just Do It!", embedUrl: 'https://www.youtube.com/embed/ZXsQAXx_ao0' },
  { title: "Dream \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/g-jwWYX7Jlo' },
  { title: "Why Do We Fall", embedUrl: 'https://www.youtube.com/embed/mgmVOuLgFB0' },
  { title: "Unstoppable", embedUrl: 'https://www.youtube.com/embed/9z4Kft47kBM' },
  { title: "Jim Carrey Commencement Speech", embedUrl: 'https://www.youtube.com/embed/_ok0PXY7HhU' },
  { title: "Arnold Schwarzenegger \u2013 6 Rules of Success", embedUrl: 'https://www.youtube.com/embed/ptcqyPg1zus' },
  { title: "Eric Thomas \u2013 How Bad Do You Want It", embedUrl: 'https://www.youtube.com/embed/5fsm-QbN9r8' },
  { title: "Motivational Speech (Reddit: This always stands out)", embedUrl: 'https://www.youtube.com/embed/Ela3ChTzFcA' },
  { title: "Oh, The Places You'll Go \u2013 John Lithgow", embedUrl: 'https://www.youtube.com/embed/9aCe6jPxH6I' },
  { title: "Al Pacino \u2013 Any Given Sunday Inches Speech", embedUrl: 'https://www.youtube.com/embed/vck0lHkE1Zg' },
  { title: "The Time You Have (In JellyBeans)", embedUrl: 'https://www.youtube.com/embed/BOksW_NabEk' },
  { title: "Good Will Hunting \u2013 Park Scene", embedUrl: 'https://www.youtube.com/embed/S-rB0pHI9fU' },
  { title: "Never, Ever Give Up \u2013 Arthur's Transformation", embedUrl: 'https://www.youtube.com/embed/bN6YLb-lh8I' },
  { title: "A Pep Talk from Kid President", embedUrl: 'https://www.youtube.com/embed/l-gQLqv9f4o' },
  { title: "The Power of Words", embedUrl: 'https://www.youtube.com/embed/Hzgzim5m7oU' },
  { title: "Dead Poets Society \u2013 Carpe Diem", embedUrl: 'https://www.youtube.com/embed/vyQLaTG0j5Y' },
  { title: "Sacrifice \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/W8iCWeHwhOU' },
  { title: "Rocky Balboa Inspirational Speech", embedUrl: 'https://www.youtube.com/embed/m8VQS0X4mZQ' },
  { title: "Entrepreneurs Can Change the World", embedUrl: 'https://www.youtube.com/embed/IyzwawewYM8' },
  { title: "Versus \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/L0MK7qz13bU' },
  { title: "How Successful People Think", embedUrl: 'https://www.youtube.com/embed/hXvkX4nfiTQ' },
  { title: "Prove Them Wrong", embedUrl: 'https://www.youtube.com/embed/MtN1YnoL46Q' },
  { title: "How Bad Do You Want It \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/lsSC2vx7zFQ' },
  { title: "Everybody Wants to Be a Beast", embedUrl: 'https://www.youtube.com/embed/fc7JixSJvx0' },
  { title: "One of the Best Motivational Videos", embedUrl: 'https://www.youtube.com/embed/3sK3wJAxGfs' },
  { title: "Rocky \u2013 5 Lessons of Life", embedUrl: 'https://www.youtube.com/embed/Nf1WEEOrI7k' },
  { title: "Unbroken \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/tkkCGErvlS8' },
  { title: "Oprah Winfrey \u2013 Intention Speech", embedUrl: 'https://www.youtube.com/embed/Wz3WXXYJbzA' },
  { title: "Hidden Figures \u2013 Be First", embedUrl: 'https://www.youtube.com/embed/NyeyvACkUAE' },
  { title: "Steve Jobs \u2013 Love What You Do (Stanford speech excerpt)", embedUrl: 'https://www.youtube.com/embed/UF8uR6Z6KLc' },
  { title: "Friday Night Lights \u2013 Perfect Speech", embedUrl: 'https://www.youtube.com/embed/MPrC228Jt2g' },
  { title: "Glengarry Glen Ross \u2013 Always Be Closing", embedUrl: 'https://www.youtube.com/embed/y-AXTx4PcKI' },
  { title: "Wolf of Wall Street \u2013 Sell Me This Pen", embedUrl: 'https://www.youtube.com/embed/p7X7yWF6kKs' },
  { title: "The Young Guru Motivational Kid", embedUrl: 'https://www.youtube.com/embed/PZLNIc2jWgw' },
  { title: "Erin Brockovich \u2013 The Long Game", embedUrl: 'https://www.youtube.com/embed/UF7ab8wVZf0' },
  { title: "Denzel Washington \u2013 Fall Forward", embedUrl: 'https://www.youtube.com/embed/pG5IDsmH0CQ' },
  { title: "Jocko Willink \u2013 Good", embedUrl: 'https://www.youtube.com/embed/IdTMDpizis8' },
  { title: "David Goggins \u2013 Can't Hurt Me", embedUrl: 'https://www.youtube.com/embed/Bo9QnYvnkM0' },
  { title: "Les Brown \u2013 It\u2019s Not Over Until You Win", embedUrl: 'https://www.youtube.com/embed/fboAHxkDhno' },
  { title: "Inky Johnson \u2013 Facing Adversity", embedUrl: 'https://www.youtube.com/embed/mhZKMHWi-l0' },
  { title: "Jocko Willink \u2013 Extreme Ownership", embedUrl: 'https://www.youtube.com/embed/R_Ac1rxj6NQ' },
  { title: "Eric Thomas \u2013 I Can, I Will, I Must", embedUrl: 'https://www.youtube.com/embed/ROhkvxI7R_o' },
  { title: "Kobe Bryant \u2013 Mamba Mentality", embedUrl: 'https://www.youtube.com/embed/ghFy5XAHZZM' },
  { title: "Admiral McRaven \u2013 Make Your Bed", embedUrl: 'https://www.youtube.com/embed/yaQZFhrW0fI' },
  { title: "Nick Vujicic \u2013 No Arms, No Legs, No Worries", embedUrl: 'https://www.youtube.com/embed/YaphY7vSehY' },
  { title: "Les Brown \u2013 You Gotta Be Hungry", embedUrl: 'https://www.youtube.com/embed/5DiNJmjl1Fg' },
  { title: "Jim Rohn \u2013 Why Not You?", embedUrl: 'https://www.youtube.com/embed/JTm4JUsH6Ew' },
  { title: "Will Smith \u2013 Skydiving Story", embedUrl: 'https://www.youtube.com/embed/Q1c1fH_S-KU' },
  { title: "Sylvester Stallone \u2013 Speech to His Son", embedUrl: 'https://www.youtube.com/embed/mRf3-JkwqfU' },
  { title: "Eric Thomas \u2013 Pain Is Temporary", embedUrl: 'https://www.youtube.com/embed/YjxSjMK0u7Y' },
  { title: "David Goggins \u2013 Stay Hard", embedUrl: 'https://www.youtube.com/embed/xbs88df431w' },
  { title: "Les Brown \u2013 It\u2019s Possible", embedUrl: 'https://www.youtube.com/embed/gpvCc06dxHY' },
  { title: "Arnold Schwarzenegger \u2013 Motivational Speech", embedUrl: 'https://www.youtube.com/embed/uY1h2FDUZsA' },
  { title: "Jocko Willink \u2013 Discipline Equals Freedom", embedUrl: 'https://www.youtube.com/embed/FGsuv1P_sQw' },
  { title: "Inky Johnson \u2013 Heart of a Champion", embedUrl: 'https://www.youtube.com/embed/mLRJGUpfJRk' },
  { title: "Simon Sinek \u2013 Start With Why", embedUrl: 'https://www.youtube.com/embed/u4ZoJKF_VuA' },
  { title: "Les Brown \u2013 Get Up and Get It Done", embedUrl: 'https://www.youtube.com/embed/QwM5X0TIpMw' },
  { title: "Denzel Washington \u2013 Put God First", embedUrl: 'https://www.youtube.com/embed/HxCkVZ1KPGw' },
  { title: "Jocko Willink \u2013 Day of Ownership", embedUrl: 'https://www.youtube.com/embed/ldPvEBYbQH0' },
  { title: "Inky Johnson \u2013 Better Not Bitter", embedUrl: 'https://www.youtube.com/embed/1F-qkAkTzXg' },
  { title: "CT Fletcher \u2013 I Command You to Grow", embedUrl: 'https://www.youtube.com/embed/v9C19VjJ8mQ' },
  { title: "David Goggins \u2013 Accountability Mirror", embedUrl: 'https://www.youtube.com/embed/B_HnEaSQ6gw' },
  { title: "Tyrese Gibson \u2013 Motivation", embedUrl: 'https://www.youtube.com/embed/i7_YXNWwK1M' },
  { title: "Joe Rogan \u2013 Best Advice Ever", embedUrl: 'https://www.youtube.com/embed/AWPl2D28A50' },
  { title: "Les Brown \u2013 You Deserve", embedUrl: 'https://www.youtube.com/embed/sFxWPhxL9xs' },
  { title: "David Goggins \u2013 Stay Hard (New)", embedUrl: 'https://www.youtube.com/embed/mya3md0bKsA' },
  { title: "Eric Thomas \u2013 Be Phenomenal", embedUrl: 'https://www.youtube.com/embed/Kx8Ndu7ID3' },
  { title: "Henry Rollins \u2013 Self Confidence", embedUrl: 'https://www.youtube.com/embed/SnY4hG10zfI' },
  { title: "Jocko Willink \u2013 Stop Worrying", embedUrl: 'https://www.youtube.com/embed/7x7Dsgw5Ogg' },
  { title: "David Goggins \u2013 Choose to be Uncommon", embedUrl: 'https://www.youtube.com/embed/dfiNn9NRyTI' },
  { title: "Arnold Schwarzenegger \u2013 Blueprint for Success", embedUrl: 'https://www.youtube.com/embed/cD1ysdLdnQc' },
  { title: "Gary Vaynerchuk \u2013 Do What You Love", embedUrl: 'https://www.youtube.com/embed/itx9F0YlUWs' },
  { title: "Inky Johnson \u2013 The Process", embedUrl: 'https://www.youtube.com/embed/FajXpGsqaN8' },
  { title: "Eric Thomas \u2013 Rise and Grind", embedUrl: 'https://www.youtube.com/embed/rBUdMna3b6s' },
  { title: "Mel Robbins \u2013 Stop Waiting for Motivation", embedUrl: 'https://www.youtube.com/embed/nIPrhTfEwb4' },
  { title: "Les Brown \u2013 The Greatness Within You", embedUrl: 'https://www.youtube.com/embed/gY7Tvg1iim4' },
  { title: "Arnold Schwarzenegger \u2013 From Bodybuilder to Governor", embedUrl: 'https://www.youtube.com/embed/9gnKo_U4v7M' },
  { title: "CT Fletcher \u2013 Strength Is Measured by Effort", embedUrl: 'https://www.youtube.com/embed/CbJBsjSBmFU' },
  { title: "Jocko Willink \u2013 Fight", embedUrl: 'https://www.youtube.com/embed/uhX-4B4Z8WU' },
  { title: "David Goggins \u2013 Embrace the Suck", embedUrl: 'https://www.youtube.com/embed/8iG1B8X_9h8' },
  { title: "Kobe Bryant \u2013 Work Harder", embedUrl: 'https://www.youtube.com/embed/gvuMq_x-lEk' },
  { title: "Inky Johnson \u2013 Courage to Keep Going", embedUrl: 'https://www.youtube.com/embed/Uxywth0DI5Y' },
  { title: "Eric Thomas \u2013 Stay Ready", embedUrl: 'https://www.youtube.com/embed/7-bk5cbRfXM' },
  { title: "Les Brown \u2013 If You Can Look Up, You Can Get Up", embedUrl: 'https://www.youtube.com/embed/B8VoUYtx0kw' },
  { title: "David Goggins \u2013 Mindset Is Everything", embedUrl: 'https://www.youtube.com/embed/fOmQsTfHIRI' },
  { title: "Jocko Willink \u2013 Believe in Yourself", embedUrl: 'https://www.youtube.com/embed/5fQE-J3s9cE' },
  { title: "Les Brown \u2013 Only Limits Are in Your Mind", embedUrl: 'https://www.youtube.com/embed/yIVuxrSi5xs' },
  { title: "Eric Thomas \u2013 Greatness Is Upon You", embedUrl: 'https://www.youtube.com/embed/mTAm-hUl7bA' },
  { title: "Inky Johnson \u2013 I Can't Lose", embedUrl: 'https://www.youtube.com/embed/Kc1n90wFnHU' },
  { title: "CT Fletcher \u2013 Don\u2019t Just Dream, Execute", embedUrl: 'https://www.youtube.com/embed/caEiN3hn9yg' },
  { title: "Jocko Willink \u2013 Prioritize and Execute", embedUrl: 'https://www.youtube.com/embed/IEQDun9TQzg' },
  { title: "Arnold Schwarzenegger \u2013 Education of a Bodybuilder", embedUrl: 'https://www.youtube.com/embed/OYUYArX6LAQ' },
  { title: "David Goggins \u2013 You Owe You", embedUrl: 'https://www.youtube.com/embed/ZKbY94zXu7M' },
  { title: "Les Brown \u2013 It\u2019s Not Over", embedUrl: 'https://www.youtube.com/embed/kWfIqk1i6l4' },
  { title: "Eric Thomas \u2013 Keep Dreaming", embedUrl: 'https://www.youtube.com/embed/k9M9Ewqy9tg' },
  { title: "Inky Johnson \u2013 Be Inspired by Failure", embedUrl: 'https://www.youtube.com/embed/wB7edH2JWgw' },
  { title: "CT Fletcher \u2013 Working Through Pain", embedUrl: 'https://www.youtube.com/embed/z-iFrtfv7Os' },
  { title: "Jocko Willink \u2013 No Weakness", embedUrl: 'https://www.youtube.com/embed/u1P6guCtcKc' },
  { title: "David Goggins \u2013 Stop Waiting for a Sign", embedUrl: 'https://www.youtube.com/embed/-O8tLy_wX2k' },
  { title: "Les Brown \u2013 The Ultimate Motivation", embedUrl: 'https://www.youtube.com/embed/g0p1dqUuQkE' },
  { title: "Eric Thomas \u2013 I Don\u2019t Care How Good You Are", embedUrl: 'https://www.youtube.com/embed/X4TbMbuggqg' },
  { title: "Inky Johnson \u2013 Stay Committed", embedUrl: 'https://www.youtube.com/embed/JzQ_7JSbzdk' },
  { title: "CT Fletcher \u2013 Set Bigger Goals", embedUrl: 'https://www.youtube.com/embed/7yEo89bV-1Q' },
  { title: "Jocko Willink \u2013 Ownership", embedUrl: 'https://www.youtube.com/embed/3R3P2bGs6j4' },
  { title: "David Goggins \u2013 Motivation vs Discipline", embedUrl: 'https://www.youtube.com/embed/-8y0kJzAD7k' },
  { title: "Les Brown \u2013 Don\u2019t Stop", embedUrl: 'https://www.youtube.com/embed/2aYGP0DsLWo' },
  { title: "Eric Thomas \u2013 Pain Is Your Friend", embedUrl: 'https://www.youtube.com/embed/VSz-fck-eEw' },
  { title: "Inky Johnson \u2013 You Can't Cheat the Grind", embedUrl: 'https://www.youtube.com/embed/Jou5FeCh7_g' },
  { title: "CT Fletcher \u2013 You Must Believe", embedUrl: 'https://www.youtube.com/embed/yH4Hu-dZpZ0' },
  { title: "Jocko Willink \u2013 Overcome Obstacles", embedUrl: 'https://www.youtube.com/embed/3tQqN5Bi9fA' },
  { title: "David Goggins \u2013 Stay True to Yourself", embedUrl: 'https://www.youtube.com/embed/pXivFz5ZL58' },
  { title: "Rocky \u2013 Going the Distance", embedUrl: 'https://www.youtube.com/embed/N0LlElkRO8k' },
  { title: "The Dark Knight Rises \u2013 Bane\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/lE6xp3dc9hA' },
  { title: "Braveheart \u2013 Freedom Speech", embedUrl: 'https://www.youtube.com/embed/gr_OpFxCx-A' },
  { title: "Miracle \u2013 Pregame Speech", embedUrl: 'https://www.youtube.com/embed/mE4XJnvkS-s' },
  { title: "Lean on Me \u2013 Coach\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/CHU2iIbTxVM' },
  { title: "Coach Carter \u2013 Our Deepest Fear", embedUrl: 'https://www.youtube.com/embed/Yc2FyX8UrzI' },
  { title: "Pursuit of Happyness \u2013 Don\u2019t Ever Let Someone Tell You", embedUrl: 'https://www.youtube.com/embed/OMuD-ZoD_ZY' },
  { title: "Facing the Giants \u2013 Death Crawl", embedUrl: 'https://www.youtube.com/embed/gAiYXr6t5C8' },
  { title: "Remember the Titans \u2013 Coach Boone\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/shpT8BZp9zo' },
  { title: "Any Given Sunday \u2013 Pre-Game Speech", embedUrl: 'https://www.youtube.com/embed/9A_2YZAgP78' },
  { title: "300 \u2013 This Is Where We Fight", embedUrl: 'https://www.youtube.com/embed/Wmxq3nPmVg0' },
  { title: "Lord of the Rings \u2013 Sam\u2019s Speech to Frodo", embedUrl: 'https://www.youtube.com/embed/bH-Tz2XYKVE' },
  { title: "Gladiator \u2013 What We Do in Life Echoes in Eternity", embedUrl: 'https://www.youtube.com/embed/Cpr_7togTWI' },
  { title: "The Blind Side \u2013 Protect Your Family", embedUrl: 'https://www.youtube.com/embed/p05JE9CMEiE' },
  { title: "The Replacements \u2013 Greatness Isn\u2019t Measured By the Scoreboard", embedUrl: 'https://www.youtube.com/embed/a3WL1ybw5ao' },
  { title: "Moneyball \u2013 It\u2019s a Process", embedUrl: 'https://www.youtube.com/embed/coYSWwtY6Bs' },
  { title: "Dead Poets Society \u2013 O Captain My Captain", embedUrl: 'https://www.youtube.com/embed/Sn_9VibQXpc' },
  { title: "Never Give Up \u2013 Nick Vujicic", embedUrl: 'https://www.youtube.com/embed/6P2nPI6CTlc' },
  { title: "Don\u2019t Quit \u2013 Richard Williams", embedUrl: 'https://www.youtube.com/embed/yb1YwslOdaY' },
  { title: "Get Up and Fail Again \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/EASYUuO6C6' },
  { title: "The Man in the Arena \u2013 Theodore Roosevelt", embedUrl: 'https://www.youtube.com/embed/okbqL0PLiEY' },
  { title: "Man on Fire \u2013 Training Speech", embedUrl: 'https://www.youtube.com/embed/4H5IQuvty1M' },
  { title: "The Matrix \u2013 There Is No Spoon", embedUrl: 'https://www.youtube.com/embed/Z7BuQFUhsRM' },
  { title: "Jerry Maguire \u2013 Show Me the Money", embedUrl: 'https://www.youtube.com/embed/OaiSHcHM0PA' },
  { title: "The Great Dictator \u2013 Final Speech", embedUrl: 'https://www.youtube.com/embed/w8HdOHrc3OQ' },
  { title: "In Pursuit of Happyness \u2013 Interview Scene", embedUrl: 'https://www.youtube.com/embed/JjzKd_RvCVw' },
  { title: "Cinderella Man \u2013 Motivational Speech", embedUrl: 'https://www.youtube.com/embed/1U3LQb9Co90' },
  { title: "Fight for Your Life \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/Ja9BjjsFUas' },
  { title: "If by Rudyard Kipling \u2013 Poem", embedUrl: 'https://www.youtube.com/embed/RyiH4JillW8' },
  { title: "When Life Knocks You Down", embedUrl: 'https://www.youtube.com/embed/clbeZjwQCkI' },
  { title: "Muhammad Ali \u2013 I Am the Greatest", embedUrl: 'https://www.youtube.com/embed/aZxGSCHROiE' },
  { title: "No Excuses \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/x4d4teR0xT4' },
  { title: "Secret to Success \u2013 Inky Johnson", embedUrl: 'https://www.youtube.com/embed/1PT1P3tnUwY' },
  { title: "Where You At \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/o68sPaO1dxM' },
  { title: "Pressure Makes Diamonds \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/1mT9Jm9XGi8' },
  { title: "The Comfort Zone \u2013 Where Dreams Go to Die", embedUrl: 'https://www.youtube.com/embed/T4EF7Ch6HbA' },
  { title: "I\u2019ll Die Trying \u2013 CT Fletcher", embedUrl: 'https://www.youtube.com/embed/xb2hXIdSX60' },
  { title: "The Grind Can\u2019t Stop \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/kV9X6v7QO4c' },
  { title: "Dare to Dream Big \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/wXgdoBLgRuM' },
  { title: "I Have a Dream \u2013 Martin Luther King Jr. (Excerpt)", embedUrl: 'https://www.youtube.com/embed/I47Y6VHc3Ms' },
  { title: "Navy SEALs Training \u2013 Overcome", embedUrl: 'https://www.youtube.com/embed/7DSR0Nk9_Ao' },
  { title: "No More Excuses \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/VH_DkxxzyVM' },
  { title: "Run When You\u2019re Not Ready \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/K3jCwUc3f4M' },
  { title: "Winners Always Keep Going \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/eNmuPf8h4Co' },
  { title: "Pain Is Temporary \u2013 Lance Armstrong", embedUrl: 'https://www.youtube.com/embed/k4jNCi_9HAI' },
  { title: "One More Round \u2013 Rocky IV", embedUrl: 'https://www.youtube.com/embed/LQ2bGEvT_TQ' },
  { title: "Coach Carter \u2013 Timeout Speech", embedUrl: 'https://www.youtube.com/embed/C7-v3vc0Pxk' },
  { title: "Rudy \u2013 Team Speech", embedUrl: 'https://www.youtube.com/embed/D9Uafj5zPGM' },
  { title: "Prince Ea \u2013 Everybody Dies, Not Everybody Lives", embedUrl: 'https://www.youtube.com/embed/U_xXGQSP49A' },
  { title: "Prince Ea \u2013 I Am NOT Black, You Are NOT White", embedUrl: 'https://www.youtube.com/embed/5GJuthrSfuQ' },
  { title: "ET \u2013 Keep Your Dreams Intangible", embedUrl: 'https://www.youtube.com/embed/V3w9e1X5dnA' },
  { title: "David Goggins \u2013 Choose to Be Uncommon", embedUrl: 'https://www.youtube.com/embed/Bd4h2NyOGI' },
  { title: "David Goggins \u2013 40% Rule", embedUrl: 'https://www.youtube.com/embed/zMRrNY0pzfw' },
  { title: "The Marathon Continues \u2013 Nipsey Hussle", embedUrl: 'https://www.youtube.com/embed/kuMa8Gcer64' },
  { title: "Impossible Is Nothing \u2013 Muhammad Ali", embedUrl: 'https://www.youtube.com/embed/CuV-0d04Fno' },
  { title: "I Will Win \u2013 Nick Vujicic", embedUrl: 'https://www.youtube.com/embed/B1Y9XxAiRyk' },
  { title: "Make Today Count \u2013 John Maxwell", embedUrl: 'https://www.youtube.com/embed/nD7ar_F58eU' },
  { title: "I Won\u2019t Be Broken \u2013 Inky Johnson", embedUrl: 'https://www.youtube.com/embed/liBIlbWzX_w' },
  { title: "The Man Who Loves Walking \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/oK_HgGSyMFc' },
  { title: "If You Can\u2019t Fly, Run \u2013 MLK Jr.", embedUrl: 'https://www.youtube.com/embed/0GxrV5iyIe4' },
  { title: "Sheer Will \u2013 Will Smith", embedUrl: 'https://www.youtube.com/embed/VPZ2IOgMLXs' },
  { title: "Be Phenomenal or Be Forgotten \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/FC1zH5Pj4xc' },
  { title: "Count On It \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/Hn5E5yq9k28' },
  { title: "Mind Over Matter \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/Byvuwv3NuFI' },
  { title: "Every Set Counts \u2013 CT Fletcher", embedUrl: 'https://www.youtube.com/embed/QWD9JYwCMXA' },
  { title: "Stay Hard \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/vTTvDa3p034' },
  { title: "Another Level \u2013 Ben Lionel Scott", embedUrl: 'https://www.youtube.com/embed/n2TTdwhzpxQ' },
  { title: "Grind 100 \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/4_5cgRIwna8' },
  { title: "Memorial Day \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/1ncsW1y0U90' },
  { title: "Rise and Shine", embedUrl: 'https://www.youtube.com/embed/hbkZrOU1Zag' },
  { title: "Shia LaBeouf \u2013 Just Do It!", embedUrl: 'https://www.youtube.com/embed/ZXsQAXx_ao0' },
  { title: "Dream \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/g-jwWYX7Jlo' },
  { title: "Why Do We Fall", embedUrl: 'https://www.youtube.com/embed/mgmVOuLgFB0' },
  { title: "Unstoppable", embedUrl: 'https://www.youtube.com/embed/9z4Kft47kBM' },
  { title: "Jim Carrey Commencement Speech", embedUrl: 'https://www.youtube.com/embed/_ok0PXY7HhU' },
  { title: "Arnold Schwarzenegger \u2013 6 Rules of Success", embedUrl: 'https://www.youtube.com/embed/ptcqyPg1zus' },
  { title: "Eric Thomas \u2013 How Bad Do You Want It", embedUrl: 'https://www.youtube.com/embed/5fsm-QbN9r8' },
  { title: "Motivational Speech (Reddit: This always stands out)", embedUrl: 'https://www.youtube.com/embed/Ela3ChTzFcA' },
  { title: "Oh, The Places You'll Go \u2013 John Lithgow", embedUrl: 'https://www.youtube.com/embed/9aCe6jPxH6I' },
  { title: "Al Pacino \u2013 Any Given Sunday Inches Speech", embedUrl: 'https://www.youtube.com/embed/vck0lHkE1Zg' },
  { title: "The Time You Have (In JellyBeans)", embedUrl: 'https://www.youtube.com/embed/BOksW_NabEk' },
  { title: "Good Will Hunting \u2013 Park Scene", embedUrl: 'https://www.youtube.com/embed/S-rB0pHI9fU' },
  { title: "Never, Ever Give Up \u2013 Arthur's Transformation", embedUrl: 'https://www.youtube.com/embed/bN6YLb-lh8I' },
  { title: "A Pep Talk from Kid President", embedUrl: 'https://www.youtube.com/embed/l-gQLqv9f4o' },
  { title: "The Power of Words", embedUrl: 'https://www.youtube.com/embed/Hzgzim5m7oU' },
  { title: "Dead Poets Society \u2013 Carpe Diem", embedUrl: 'https://www.youtube.com/embed/vyQLaTG0j5Y' },
  { title: "Sacrifice \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/W8iCWeHwhOU' },
  { title: "Rocky Balboa Inspirational Speech", embedUrl: 'https://www.youtube.com/embed/m8VQS0X4mZQ' },
  { title: "Entrepreneurs Can Change the World", embedUrl: 'https://www.youtube.com/embed/IyzwawewYM8' },
  { title: "Versus \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/L0MK7qz13bU' },
  { title: "How Successful People Think", embedUrl: 'https://www.youtube.com/embed/hXvkX4nfiTQ' },
  { title: "Prove Them Wrong", embedUrl: 'https://www.youtube.com/embed/MtN1YnoL46Q' },
  { title: "How Bad Do You Want It \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/lsSC2vx7zFQ' },
  { title: "Everybody Wants to Be a Beast", embedUrl: 'https://www.youtube.com/embed/fc7JixSJvx0' },
  { title: "One of the Best Motivational Videos", embedUrl: 'https://www.youtube.com/embed/3sK3wJAxGfs' },
  { title: "Rocky \u2013 5 Lessons of Life", embedUrl: 'https://www.youtube.com/embed/Nf1WEEOrI7k' },
  { title: "Unbroken \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/tkkCGErvlS8' },
  { title: "Oprah Winfrey \u2013 Intention Speech", embedUrl: 'https://www.youtube.com/embed/Wz3WXXYJbzA' },
  { title: "Hidden Figures \u2013 Be First", embedUrl: 'https://www.youtube.com/embed/NyeyvACkUAE' },
  { title: "Steve Jobs \u2013 Love What You Do (Stanford speech excerpt)", embedUrl: 'https://www.youtube.com/embed/UF8uR6Z6KLc' },
  { title: "Friday Night Lights \u2013 Perfect Speech", embedUrl: 'https://www.youtube.com/embed/MPrC228Jt2g' },
  { title: "Glengarry Glen Ross \u2013 Always Be Closing", embedUrl: 'https://www.youtube.com/embed/y-AXTx4PcKI' },
  { title: "Wolf of Wall Street \u2013 Sell Me This Pen", embedUrl: 'https://www.youtube.com/embed/p7X7yWF6kKs' },
  { title: "The Young Guru Motivational Kid", embedUrl: 'https://www.youtube.com/embed/PZLNIc2jWgw' },
  { title: "Erin Brockovich \u2013 The Long Game", embedUrl: 'https://www.youtube.com/embed/UF7ab8wVZf0' },
  { title: "Denzel Washington \u2013 Fall Forward", embedUrl: 'https://www.youtube.com/embed/pG5IDsmH0CQ' },
  { title: "Jocko Willink \u2013 Good", embedUrl: 'https://www.youtube.com/embed/IdTMDpizis8' },
  { title: "David Goggins \u2013 Can't Hurt Me", embedUrl: 'https://www.youtube.com/embed/Bo9QnYvnkM0' },
  { title: "Les Brown \u2013 It\u2019s Not Over Until You Win", embedUrl: 'https://www.youtube.com/embed/fboAHxkDhno' },
  { title: "Inky Johnson \u2013 Facing Adversity", embedUrl: 'https://www.youtube.com/embed/mhZKMHWi-l0' },
  { title: "Jocko Willink \u2013 Extreme Ownership", embedUrl: 'https://www.youtube.com/embed/R_Ac1rxj6NQ' },
  { title: "Eric Thomas \u2013 I Can, I Will, I Must", embedUrl: 'https://www.youtube.com/embed/ROhkvxI7R_o' },
  { title: "Kobe Bryant \u2013 Mamba Mentality", embedUrl: 'https://www.youtube.com/embed/ghFy5XAHZZM' },
  { title: "Admiral McRaven \u2013 Make Your Bed", embedUrl: 'https://www.youtube.com/embed/yaQZFhrW0fI' },
  { title: "Nick Vujicic \u2013 No Arms, No Legs, No Worries", embedUrl: 'https://www.youtube.com/embed/YaphY7vSehY' },
  { title: "Les Brown \u2013 You Gotta Be Hungry", embedUrl: 'https://www.youtube.com/embed/5DiNJmjl1Fg' },
  { title: "Jim Rohn \u2013 Why Not You?", embedUrl: 'https://www.youtube.com/embed/JTm4JUsH6Ew' },
  { title: "Will Smith \u2013 Skydiving Story", embedUrl: 'https://www.youtube.com/embed/Q1c1fH_S-KU' },
  { title: "Sylvester Stallone \u2013 Speech to His Son", embedUrl: 'https://www.youtube.com/embed/mRf3-JkwqfU' },
  { title: "Eric Thomas \u2013 Pain Is Temporary", embedUrl: 'https://www.youtube.com/embed/YjxSjMK0u7Y' },
  { title: "David Goggins \u2013 Stay Hard", embedUrl: 'https://www.youtube.com/embed/xbs88df431w' },
  { title: "Les Brown \u2013 It\u2019s Possible", embedUrl: 'https://www.youtube.com/embed/gpvCc06dxHY' },
  { title: "Arnold Schwarzenegger \u2013 Motivational Speech", embedUrl: 'https://www.youtube.com/embed/uY1h2FDUZsA' },
  { title: "Jocko Willink \u2013 Discipline Equals Freedom", embedUrl: 'https://www.youtube.com/embed/FGsuv1P_sQw' },
  { title: "Inky Johnson \u2013 Heart of a Champion", embedUrl: 'https://www.youtube.com/embed/mLRJGUpfJRk' },
  { title: "Simon Sinek \u2013 Start With Why", embedUrl: 'https://www.youtube.com/embed/u4ZoJKF_VuA' },
  { title: "Les Brown \u2013 Get Up and Get It Done", embedUrl: 'https://www.youtube.com/embed/QwM5X0TIpMw' },
  { title: "Denzel Washington \u2013 Put God First", embedUrl: 'https://www.youtube.com/embed/HxCkVZ1KPGw' },
  { title: "Jocko Willink \u2013 Day of Ownership", embedUrl: 'https://www.youtube.com/embed/ldPvEBYbQH0' },
  { title: "Inky Johnson \u2013 Better Not Bitter", embedUrl: 'https://www.youtube.com/embed/1F-qkAkTzXg' },
  { title: "CT Fletcher \u2013 I Command You to Grow", embedUrl: 'https://www.youtube.com/embed/v9C19VjJ8mQ' },
  { title: "David Goggins \u2013 Accountability Mirror", embedUrl: 'https://www.youtube.com/embed/B_HnEaSQ6gw' },
  { title: "Tyrese Gibson \u2013 Motivation", embedUrl: 'https://www.youtube.com/embed/i7_YXNWwK1M' },
  { title: "Joe Rogan \u2013 Best Advice Ever", embedUrl: 'https://www.youtube.com/embed/AWPl2D28A50' },
  { title: "Les Brown \u2013 You Deserve", embedUrl: 'https://www.youtube.com/embed/sFxWPhxL9xs' },
  { title: "David Goggins \u2013 Stay Hard (New)", embedUrl: 'https://www.youtube.com/embed/mya3md0bKsA' },
  { title: "Eric Thomas \u2013 Be Phenomenal", embedUrl: 'https://www.youtube.com/embed/Kx8Ndu7ID3' },
  { title: "Henry Rollins \u2013 Self Confidence", embedUrl: 'https://www.youtube.com/embed/SnY4hG10zfI' },
  { title: "Jocko Willink \u2013 Stop Worrying", embedUrl: 'https://www.youtube.com/embed/7x7Dsgw5Ogg' },
  { title: "David Goggins \u2013 Choose to be Uncommon", embedUrl: 'https://www.youtube.com/embed/dfiNn9NRyTI' },
  { title: "Arnold Schwarzenegger \u2013 Blueprint for Success", embedUrl: 'https://www.youtube.com/embed/cD1ysdLdnQc' },
  { title: "Gary Vaynerchuk \u2013 Do What You Love", embedUrl: 'https://www.youtube.com/embed/itx9F0YlUWs' },
  { title: "Inky Johnson \u2013 The Process", embedUrl: 'https://www.youtube.com/embed/FajXpGsqaN8' },
  { title: "Eric Thomas \u2013 Rise and Grind", embedUrl: 'https://www.youtube.com/embed/rBUdMna3b6s' },
  { title: "Mel Robbins \u2013 Stop Waiting for Motivation", embedUrl: 'https://www.youtube.com/embed/nIPrhTfEwb4' },
  { title: "Les Brown \u2013 The Greatness Within You", embedUrl: 'https://www.youtube.com/embed/gY7Tvg1iim4' },
  { title: "Arnold Schwarzenegger \u2013 From Bodybuilder to Governor", embedUrl: 'https://www.youtube.com/embed/9gnKo_U4v7M' },
  { title: "CT Fletcher \u2013 Strength Is Measured by Effort", embedUrl: 'https://www.youtube.com/embed/CbJBsjSBmFU' },
  { title: "Jocko Willink \u2013 Fight", embedUrl: 'https://www.youtube.com/embed/uhX-4B4Z8WU' },
  { title: "David Goggins \u2013 Embrace the Suck", embedUrl: 'https://www.youtube.com/embed/8iG1B8X_9h8' },
  { title: "Kobe Bryant \u2013 Work Harder", embedUrl: 'https://www.youtube.com/embed/gvuMq_x-lEk' },
  { title: "Inky Johnson \u2013 Courage to Keep Going", embedUrl: 'https://www.youtube.com/embed/Uxywth0DI5Y' },
  { title: "Eric Thomas \u2013 Stay Ready", embedUrl: 'https://www.youtube.com/embed/7-bk5cbRfXM' },
  { title: "Les Brown \u2013 If You Can Look Up, You Can Get Up", embedUrl: 'https://www.youtube.com/embed/B8VoUYtx0kw' },
  { title: "David Goggins \u2013 Mindset Is Everything", embedUrl: 'https://www.youtube.com/embed/fOmQsTfHIRI' },
  { title: "Jocko Willink \u2013 Believe in Yourself", embedUrl: 'https://www.youtube.com/embed/5fQE-J3s9cE' },
  { title: "Les Brown \u2013 Only Limits Are in Your Mind", embedUrl: 'https://www.youtube.com/embed/yIVuxrSi5xs' },
  { title: "Eric Thomas \u2013 Greatness Is Upon You", embedUrl: 'https://www.youtube.com/embed/mTAm-hUl7bA' },
  { title: "Inky Johnson \u2013 I Can't Lose", embedUrl: 'https://www.youtube.com/embed/Kc1n90wFnHU' },
  { title: "CT Fletcher \u2013 Don\u2019t Just Dream, Execute", embedUrl: 'https://www.youtube.com/embed/caEiN3hn9yg' },
  { title: "Jocko Willink \u2013 Prioritize and Execute", embedUrl: 'https://www.youtube.com/embed/IEQDun9TQzg' },
  { title: "Arnold Schwarzenegger \u2013 Education of a Bodybuilder", embedUrl: 'https://www.youtube.com/embed/OYUYArX6LAQ' },
  { title: "David Goggins \u2013 You Owe You", embedUrl: 'https://www.youtube.com/embed/ZKbY94zXu7M' },
  { title: "Les Brown \u2013 It\u2019s Not Over", embedUrl: 'https://www.youtube.com/embed/kWfIqk1i6l4' },
  { title: "Eric Thomas \u2013 Keep Dreaming", embedUrl: 'https://www.youtube.com/embed/k9M9Ewqy9tg' },
  { title: "Inky Johnson \u2013 Be Inspired by Failure", embedUrl: 'https://www.youtube.com/embed/wB7edH2JWgw' },
  { title: "CT Fletcher \u2013 Working Through Pain", embedUrl: 'https://www.youtube.com/embed/z-iFrtfv7Os' },
  { title: "Jocko Willink \u2013 No Weakness", embedUrl: 'https://www.youtube.com/embed/u1P6guCtcKc' },
  { title: "David Goggins \u2013 Stop Waiting for a Sign", embedUrl: 'https://www.youtube.com/embed/-O8tLy_wX2k' },
  { title: "Les Brown \u2013 The Ultimate Motivation", embedUrl: 'https://www.youtube.com/embed/g0p1dqUuQkE' },
  { title: "Eric Thomas \u2013 I Don\u2019t Care How Good You Are", embedUrl: 'https://www.youtube.com/embed/X4TbMbuggqg' },
  { title: "Inky Johnson \u2013 Stay Committed", embedUrl: 'https://www.youtube.com/embed/JzQ_7JSbzdk' },
  { title: "CT Fletcher \u2013 Set Bigger Goals", embedUrl: 'https://www.youtube.com/embed/7yEo89bV-1Q' },
  { title: "Jocko Willink \u2013 Ownership", embedUrl: 'https://www.youtube.com/embed/3R3P2bGs6j4' },
  { title: "David Goggins \u2013 Motivation vs Discipline", embedUrl: 'https://www.youtube.com/embed/-8y0kJzAD7k' },
  { title: "Les Brown \u2013 Don\u2019t Stop", embedUrl: 'https://www.youtube.com/embed/2aYGP0DsLWo' },
  { title: "Eric Thomas \u2013 Pain Is Your Friend", embedUrl: 'https://www.youtube.com/embed/VSz-fck-eEw' },
  { title: "Inky Johnson \u2013 You Can't Cheat the Grind", embedUrl: 'https://www.youtube.com/embed/Jou5FeCh7_g' },
  { title: "CT Fletcher \u2013 You Must Believe", embedUrl: 'https://www.youtube.com/embed/yH4Hu-dZpZ0' },
  { title: "Jocko Willink \u2013 Overcome Obstacles", embedUrl: 'https://www.youtube.com/embed/3tQqN5Bi9fA' },
  { title: "David Goggins \u2013 Stay True to Yourself", embedUrl: 'https://www.youtube.com/embed/pXivFz5ZL58' },
  { title: "Rocky \u2013 Going the Distance", embedUrl: 'https://www.youtube.com/embed/N0LlElkRO8k' },
  { title: "The Dark Knight Rises \u2013 Bane\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/lE6xp3dc9hA' },
  { title: "Braveheart \u2013 Freedom Speech", embedUrl: 'https://www.youtube.com/embed/gr_OpFxCx-A' },
  { title: "Miracle \u2013 Pregame Speech", embedUrl: 'https://www.youtube.com/embed/mE4XJnvkS-s' },
  { title: "Lean on Me \u2013 Coach\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/CHU2iIbTxVM' },
  { title: "Coach Carter \u2013 Our Deepest Fear", embedUrl: 'https://www.youtube.com/embed/Yc2FyX8UrzI' },
  { title: "Pursuit of Happyness \u2013 Don\u2019t Ever Let Someone Tell You", embedUrl: 'https://www.youtube.com/embed/OMuD-ZoD_ZY' },
  { title: "Facing the Giants \u2013 Death Crawl", embedUrl: 'https://www.youtube.com/embed/gAiYXr6t5C8' },
  { title: "Remember the Titans \u2013 Coach Boone\u2019s Speech", embedUrl: 'https://www.youtube.com/embed/shpT8BZp9zo' },
  { title: "Any Given Sunday \u2013 Pre-Game Speech", embedUrl: 'https://www.youtube.com/embed/9A_2YZAgP78' },
  { title: "300 \u2013 This Is Where We Fight", embedUrl: 'https://www.youtube.com/embed/Wmxq3nPmVg0' },
  { title: "Lord of the Rings \u2013 Sam\u2019s Speech to Frodo", embedUrl: 'https://www.youtube.com/embed/bH-Tz2XYKVE' },
  { title: "Gladiator \u2013 What We Do in Life Echoes in Eternity", embedUrl: 'https://www.youtube.com/embed/Cpr_7togTWI' },
  { title: "The Blind Side \u2013 Protect Your Family", embedUrl: 'https://www.youtube.com/embed/p05JE9CMEiE' },
  { title: "The Replacements \u2013 Greatness Isn\u2019t Measured By the Scoreboard", embedUrl: 'https://www.youtube.com/embed/a3WL1ybw5ao' },
  { title: "Moneyball \u2013 It\u2019s a Process", embedUrl: 'https://www.youtube.com/embed/coYSWwtY6Bs' },
  { title: "Dead Poets Society \u2013 O Captain My Captain", embedUrl: 'https://www.youtube.com/embed/Sn_9VibQXpc' },
  { title: "Never Give Up \u2013 Nick Vujicic", embedUrl: 'https://www.youtube.com/embed/6P2nPI6CTlc' },
  { title: "Don\u2019t Quit \u2013 Richard Williams", embedUrl: 'https://www.youtube.com/embed/yb1YwslOdaY' },
  { title: "Get Up and Fail Again \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/EASYUuO6C6' },
  { title: "The Man in the Arena \u2013 Theodore Roosevelt", embedUrl: 'https://www.youtube.com/embed/okbqL0PLiEY' },
  { title: "Man on Fire \u2013 Training Speech", embedUrl: 'https://www.youtube.com/embed/4H5IQuvty1M' },
  { title: "The Matrix \u2013 There Is No Spoon", embedUrl: 'https://www.youtube.com/embed/Z7BuQFUhsRM' },
  { title: "Jerry Maguire \u2013 Show Me the Money", embedUrl: 'https://www.youtube.com/embed/OaiSHcHM0PA' },
  { title: "The Great Dictator \u2013 Final Speech", embedUrl: 'https://www.youtube.com/embed/w8HdOHrc3OQ' },
  { title: "In Pursuit of Happyness \u2013 Interview Scene", embedUrl: 'https://www.youtube.com/embed/JjzKd_RvCVw' },
  { title: "Cinderella Man \u2013 Motivational Speech", embedUrl: 'https://www.youtube.com/embed/1U3LQb9Co90' },
  { title: "Fight for Your Life \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/Ja9BjjsFUas' },
  { title: "If by Rudyard Kipling \u2013 Poem", embedUrl: 'https://www.youtube.com/embed/RyiH4JillW8' },
  { title: "When Life Knocks You Down", embedUrl: 'https://www.youtube.com/embed/clbeZjwQCkI' },
  { title: "Muhammad Ali \u2013 I Am the Greatest", embedUrl: 'https://www.youtube.com/embed/aZxGSCHROiE' },
  { title: "No Excuses \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/x4d4teR0xT4' },
  { title: "Secret to Success \u2013 Inky Johnson", embedUrl: 'https://www.youtube.com/embed/1PT1P3tnUwY' },
  { title: "Where You At \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/o68sPaO1dxM' },
  { title: "Pressure Makes Diamonds \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/1mT9Jm9XGi8' },
  { title: "The Comfort Zone \u2013 Where Dreams Go to Die", embedUrl: 'https://www.youtube.com/embed/T4EF7Ch6HbA' },
  { title: "I\u2019ll Die Trying \u2013 CT Fletcher", embedUrl: 'https://www.youtube.com/embed/xb2hXIdSX60' },
  { title: "The Grind Can\u2019t Stop \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/kV9X6v7QO4c' },
  { title: "Dare to Dream Big \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/wXgdoBLgRuM' },
  { title: "I Have a Dream \u2013 Martin Luther King Jr. (Excerpt)", embedUrl: 'https://www.youtube.com/embed/I47Y6VHc3Ms' },
  { title: "Navy SEALs Training \u2013 Overcome", embedUrl: 'https://www.youtube.com/embed/7DSR0Nk9_Ao' },
  { title: "No More Excuses \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/VH_DkxxzyVM' },
  { title: "Run When You\u2019re Not Ready \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/K3jCwUc3f4M' },
  { title: "Winners Always Keep Going \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/eNmuPf8h4Co' },
  { title: "Pain Is Temporary \u2013 Lance Armstrong", embedUrl: 'https://www.youtube.com/embed/k4jNCi_9HAI' },
  { title: "One More Round \u2013 Rocky IV", embedUrl: 'https://www.youtube.com/embed/LQ2bGEvT_TQ' },
  { title: "Coach Carter \u2013 Timeout Speech", embedUrl: 'https://www.youtube.com/embed/C7-v3vc0Pxk' },
  { title: "Rudy \u2013 Team Speech", embedUrl: 'https://www.youtube.com/embed/D9Uafj5zPGM' },
  { title: "Prince Ea \u2013 Everybody Dies, Not Everybody Lives", embedUrl: 'https://www.youtube.com/embed/U_xXGQSP49A' },
  { title: "Prince Ea \u2013 I Am NOT Black, You Are NOT White", embedUrl: 'https://www.youtube.com/embed/5GJuthrSfuQ' },
  { title: "ET \u2013 Keep Your Dreams Intangible", embedUrl: 'https://www.youtube.com/embed/V3w9e1X5dnA' },
  { title: "David Goggins \u2013 Choose to Be Uncommon", embedUrl: 'https://www.youtube.com/embed/Bd4h2NyOGI' },
  { title: "David Goggins \u2013 40% Rule", embedUrl: 'https://www.youtube.com/embed/zMRrNY0pzfw' },
  { title: "The Marathon Continues \u2013 Nipsey Hussle", embedUrl: 'https://www.youtube.com/embed/kuMa8Gcer64' },
  { title: "Impossible Is Nothing \u2013 Muhammad Ali", embedUrl: 'https://www.youtube.com/embed/CuV-0d04Fno' },
  { title: "I Will Win \u2013 Nick Vujicic", embedUrl: 'https://www.youtube.com/embed/B1Y9XxAiRyk' },
  { title: "Make Today Count \u2013 John Maxwell", embedUrl: 'https://www.youtube.com/embed/nD7ar_F58eU' },
  { title: "I Won\u2019t Be Broken \u2013 Inky Johnson", embedUrl: 'https://www.youtube.com/embed/liBIlbWzX_w' },
  { title: "The Man Who Loves Walking \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/oK_HgGSyMFc' },
  { title: "If You Can\u2019t Fly, Run \u2013 MLK Jr.", embedUrl: 'https://www.youtube.com/embed/0GxrV5iyIe4' },
  { title: "Sheer Will \u2013 Will Smith", embedUrl: 'https://www.youtube.com/embed/VPZ2IOgMLXs' },
  { title: "Be Phenomenal or Be Forgotten \u2013 Eric Thomas", embedUrl: 'https://www.youtube.com/embed/FC1zH5Pj4xc' },
  { title: "Count On It \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/Hn5E5yq9k28' },
  { title: "Mind Over Matter \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/Byvuwv3NuFI' },
  { title: "Every Set Counts \u2013 CT Fletcher", embedUrl: 'https://www.youtube.com/embed/QWD9JYwCMXA' },
  { title: "Stay Hard \u2013 David Goggins", embedUrl: 'https://www.youtube.com/embed/vTTvDa3p034' },
  { title: "Another Level \u2013 Ben Lionel Scott", embedUrl: 'https://www.youtube.com/embed/n2TTdwhzpxQ' },
  { title: "Grind 100 \u2013 Les Brown", embedUrl: 'https://www.youtube.com/embed/4_5cgRIwna8' },
  { title: "Memorial Day \u2013 Jocko Willink", embedUrl: 'https://www.youtube.com/embed/1ncsW1y0U90' },
  { title: "Rise and Shine", embedUrl: 'https://www.youtube.com/embed/hbkZrOU1Zag' },
  { title: "Shia LaBeouf \u2013 Just Do It!", embedUrl: 'https://www.youtube.com/embed/ZXsQAXx_ao0' },
  { title: "Dream \u2013 Motivational Video", embedUrl: 'https://www.youtube.com/embed/g-jwWYX7Jlo' },
];

// Exporting is disabled for browser compatibility. The `videos` array is
// defined in the global scope so script.js can access it directly.
// export default videos;
